eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka
management:
  tracing:
    sampling:
      probability: 1.0
server:
  port: 0
spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring:
          json:
            type:
              mapping: event:net.bobdb.OrderPlacedEvent
      value-serializer: org.springframework.kafka.support.deserializer.JsonDeserializer

