myapp:
  openapi:
    dev-url: http://localhost:8080/
    prod-url: https://myapp.net/stuff
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka
logging:
  level:
    root: INFO
management:
  tracing:
    sampling:
      probability: 1.0
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: openapi
          predicates:
            - Path=/v3/api-docs/**
          uri: http://localhost:8080
        - id: swagger
          predicates:
            - Path=/swagger-ui/**
          uri: http://localhost:8080
        - id: product-service
          predicates:
            - Path=/api/products/**
          uri: lb://product-service
        - id: product-swagger
          predicates:
            - Path=/products/v3/**
          uri: lb://product-service
          filters:
            - SetPath=/v3/api-docs
        - id: order-service
          predicates:
            - Path=/api/orders/**
          uri: lb://order-service
        - id: order-swagger
          predicates:
            - Path=/orders/v3/**
          uri: lb://order-service
          filters:
            - SetPath=/v3/api-docs
        - id: inventory-service
          predicates:
            - Path=/api/inventory/**
          uri: lb://inventory-service
        - id: inventory-swagger
          predicates:
            - Path=/inventory/v3/**
          uri: lb://inventory-service
          filters:
            - SetPath=/v3/api-docs
        - id: discovery-service
          predicates:
            - Path=/eureka/web
          uri: http://localhost:8761
          filters:
            - SetPath=/
        - id: discovery-service-static
          predicates:
            - Path=/eureka/**
          uri: http://localhost:8761

  main:
    web-application-type: reactive

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /orders/v3/api-docs
        name: Order Service
      - url: /products/v3/api-docs
        name: Products Service
      - url: /inventory/v3/api-docs
        name: Inventory Service
