eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka
logging:
  level:
    root: INFO
management:
  tracing:
    sampling:
      probability: 1.0
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        -   id: product-service
            predicates:
              - Path=/api/products/**
            uri: lb://product-service
        -   id: order-service
            predicates:
              - Path=/api/orders/**
            uri: lb://order-service
        -   id: order-service-swagger
            predicates:
              - Path=/api/orders/swagger-ui/**
            uri: http://localhost:8088
            filters:
              - SetPath=/
        -   id: discovery-service
            predicates:
              - Path=/eureka/web
            uri: http://localhost:8761
            filters:
              - SetPath=/
        -   id: discovery-service-static
            predicates:
              - Path=/eureka/**
            uri: http://localhost:8761
        -   id: inventory-service
            predicates:
              - Path=/api/inventory/**
            uri: lb://inventory-service
  main:
    web-application-type: reactive