app:
  eureka:
    password: password
    username: eureka
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka
  instance:
    hostname: localhost
management:
  tracing:
    sampling:
      probability: 1.0
server:
  port: 8761
spring:
  zipkin:
    base-url: http://localhost:9411